// <auto-generated />
namespace Bardock.Flowont.Tests.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class TicketCurrentNodeRename : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TicketCurrentNodeRename));
        
        string IMigrationMetadata.Id
        {
            get { return "201407301554380_TicketCurrentNode-Rename"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
